// DemoPilot Theme — generated by /pdv-explore Phase 0
// Replace values with your brand. NEVER use Inter font or purple accent.
export const THEME = {
  accent: "#3b82f6",              // saturation < 80%, not purple family
  bg: "#0a0a0a",
  surface: "#111111",
  border: "#222222",
  text: {
    primary: "#f5f5f5",
    secondary: "#a1a1aa",
  },
  font: {
    heading: "Geist",             // alternatives: Outfit, Satoshi
    body: "Outfit",               // NOT Inter
  },
  spring: { stiffness: 100, damping: 20 },
  stagger: 40,                    // ms between staggered items
  fade: 20,                       // frames for TransitionSeries fade
} as const;
